/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginFailedImport } from './routes/login-failed'
import { Route as IndexImport } from './routes/index'
import { Route as LoginSuccessTokenImport } from './routes/login-success.$token'

// Create/Update Routes

const LoginFailedRoute = LoginFailedImport.update({
  id: '/login-failed',
  path: '/login-failed',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LoginSuccessTokenRoute = LoginSuccessTokenImport.update({
  id: '/login-success/$token',
  path: '/login-success/$token',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/login-failed': {
      id: '/login-failed'
      path: '/login-failed'
      fullPath: '/login-failed'
      preLoaderRoute: typeof LoginFailedImport
      parentRoute: typeof rootRoute
    }
    '/login-success/$token': {
      id: '/login-success/$token'
      path: '/login-success/$token'
      fullPath: '/login-success/$token'
      preLoaderRoute: typeof LoginSuccessTokenImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login-failed': typeof LoginFailedRoute
  '/login-success/$token': typeof LoginSuccessTokenRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login-failed': typeof LoginFailedRoute
  '/login-success/$token': typeof LoginSuccessTokenRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/login-failed': typeof LoginFailedRoute
  '/login-success/$token': typeof LoginSuccessTokenRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login-failed' | '/login-success/$token'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login-failed' | '/login-success/$token'
  id: '__root__' | '/' | '/login-failed' | '/login-success/$token'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginFailedRoute: typeof LoginFailedRoute
  LoginSuccessTokenRoute: typeof LoginSuccessTokenRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginFailedRoute: LoginFailedRoute,
  LoginSuccessTokenRoute: LoginSuccessTokenRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/login-failed",
        "/login-success/$token"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/login-failed": {
      "filePath": "login-failed.tsx"
    },
    "/login-success/$token": {
      "filePath": "login-success.$token.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
